version: '2'

services:
  db:
    image: postgres:10.3-alpine
  ci:
    build: .
    depends_on:
      - db
    volumes:
      - ./coverage:/task_manager/coverage/
    environment:
      - COVERALLS_REPO_TOKEN
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails webpacker:install && bundle exec rails db:create db:migrate && bundle exec rake test"
